version: "3"

services:

### Scrapy Service ###########################################
  scrapy:
    image: franten/scrapy
    build:
      context: ./scrapy
      args:
        - SCRAPY_APP_PATH=${SCRAPY_APP_PATH}
    volumes:
        - ../scrapy/biopharm:/usr/src/app
    ports:
        - "6800:6800"
    networks:
        - backend

### Postgres Service #########################################
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=franten
      - POSTGRES_PASSWORD=mypasswd
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - backend

### Volumes ##################################################
volumes:
  postgres-db:


### Networks #################################################
networks: 
  # frontend:
  #   driver: "bridge"
  backend:
    driver: "bridge"