version: "3"

services:

### Scrapy Service #########################################
  scrapy:
    image: franten/scrapy
    build:
      context: ./scrapy
      args:
        - SCRAPY_APP_PATH=${SCRAPY_APP_PATH}
    volumes:
        - ../scrapy/biopharm:/usr/src/app
    ports:
        - "6800:6800"
    networks:
        - backend

### Volumes ##################################################
# volumes:

### Networks #################################################
networks: 
  # frontend:
  #   driver: "bridge"
  backend:
    driver: "bridge"